/* tslint:disable */
/* eslint-disable */
/**
 * Cat Facts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * CatFact
 * @export
 * @interface CatFact
 */
export interface CatFact {
    /**
     * Fact
     * @type {string}
     * @memberof CatFact
     */
    fact?: string;
    /**
     * Length
     * @type {number}
     * @memberof CatFact
     */
    length?: number;
}

/**
 * Check if a given object implements the CatFact interface.
 */
export function instanceOfCatFact(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CatFactFromJSON(json: any): CatFact {
    return CatFactFromJSONTyped(json, false);
}

export function CatFactFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatFact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fact': !exists(json, 'fact') ? undefined : json['fact'],
        'length': !exists(json, 'length') ? undefined : json['length'],
    };
}

export function CatFactToJSON(value?: CatFact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fact': value.fact,
        'length': value.length,
    };
}

