/* tslint:disable */
/* eslint-disable */
/**
 * Cat Facts API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Breed,
} from '../models/index';
import {
    BreedFromJSON,
    BreedToJSON,
} from '../models/index';

export interface GetBreedsRequest {
    limit?: number;
}

/**
 * 
 */
export class BreedsApi extends runtime.BaseAPI {

    /**
     * Returns a a list of breeds
     * Get a list of breeds
     */
    async getBreedsRaw(requestParameters: GetBreedsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Breed>>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/breeds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BreedFromJSON));
    }

    /**
     * Returns a a list of breeds
     * Get a list of breeds
     */
    async getBreeds(requestParameters: GetBreedsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Breed>> {
        const response = await this.getBreedsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
